SET(CPLEX_ROOT_DIR "" CACHE PATH "cplex root directory")
SET(CONCERT_ROOT_DIR "" CACHE PATH "concert root directory")

FIND_PATH(CPLEX_INCLUDE_DIR ilcplex/cplex.h HINTS ${CPLEX_ROOT_DIR}/include)
FIND_PATH(CONCERT_INCLUDE_DIR ilconcert/iloenv.h HINTS ${CONCERT_ROOT_DIR}/include)

if(WIN32)
	FIND_PATH(CPLEX_BIN_DIR cplex124.dll HINTS ${CPLEX_ROOT_DIR}/bin/x64_win64)

    FIND_LIBRARY(CPLEX_LIBRARY_RELEASE cplex124 HINTS ${CPLEX_ROOT_DIR}/lib/x64_windows_vs2010/stat_mda)
    FIND_LIBRARY(CPLEX_LIBRARY_DEBUG cplex124 HINTS ${CPLEX_ROOT_DIR}/lib/x64_windows_vs2010/stat_mdd)
    set(CPLEX_LIBRARY "optimized;${CPLEX_LIBRARY_RELEASE};debug;${CPLEX_LIBRARY_DEBUG}")

    FIND_LIBRARY(ILOCPLEX_LIBRARY_RELEASE ilocplex HINTS ${CPLEX_ROOT_DIR}/lib/x64_windows_vs2010/stat_mda)
    FIND_LIBRARY(ILOCPLEX_LIBRARY_DEBUG ilocplex HINTS ${CPLEX_ROOT_DIR}/lib/x64_windows_vs2010/stat_mdd)
    set(ILOCPLEX_LIBRARY "optimized;${ILOCPLEX_LIBRARY_RELEASE};debug;${ILOCPLEX_LIBRARY_DEBUG}")

    FIND_LIBRARY(CONCERT_LIBRARY_RELEASE concert HINTS ${CONCERT_ROOT_DIR}/lib/x64_windows_vs2010/stat_mda)
    FIND_LIBRARY(CONCERT_LIBRARY_DEBUG concert HINTS ${CONCERT_ROOT_DIR}/lib/x64_windows_vs2010/stat_mdd)
    set(CONCERT_LIBRARY "optimized;${CONCERT_LIBRARY_RELEASE};debug;${CONCERT_LIBRARY_DEBUG}")
else()
	FIND_PATH(CPLEX_BIN_DIR libcplex124.so HINTS ${CPLEX_ROOT_DIR}/bin)

	# TODO: fill this in for linux
endif()

IF(CPLEX_LIBRARY AND ILOCPLEX_LIBRARY AND CONCERT_LIBRARY)
   SET(CPLEX_FOUND TRUE)
   MESSAGE(STATUS "Cplex found.")
ELSE()
   MESSAGE("Cplex NOT found.")
ENDIF()

